# Generated by Django 5.2.16 on 2026-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
