# Generated by Django 5.2.16 on 2026-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0005_job_experience_job_job_type_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
