# Generated by Django 5.2.16 on 2026-08-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0006_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
