# Generated by Django 5.2.16 on 2026-08-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0007_user_resume_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal_app.user')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
